name: .NET

on:
  workflow_dispatch: 
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  NuGetDirectory: ${{github.workspace}}/nuget

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x
    - name: restore dependencies
      run: dotnet restore
    - name: build
      run: dotnet build --no-restore
    - name: run tests
      run: dotnet test --no-build --verbosity normal
      env:
        COSMOSDB_CONNECTIONSTRING: ${{ secrets.COSMOSDB_CONNECTIONSTRING }}
